### ISSUE TITLE
Wrong redirect in "back" button on repository edit 

### ISSUE THREAD

**Issue by DylanGuedes** [mezuro/prezento#384]
When editing a repository, the "back" button redirect to projects index instead of the repository page (/repositories/1/edit redirect back to /projects)

**Comment by rafamanzo** [comment]
Yes, unfortunately this was necessary as part of https://github.com/mezuro/prezento/commit/e19c7cef7b539f04ab71f90e223e457348935b87.

Do you have any suggestions for a better behaviour?

Personally, I tend to say we should get rid of the back buttons because we cannot provide a consistent behaviour for them.

**Comment by DylanGuedes** [comment]
Hmm I discussed with my team and we actually like a button that lets you back directly.
The best solution imo is a [breadcrumbs](http://v4-alpha.getbootstrap.com/components/breadcrumb/), but a "back" button that directly redirects you to the previous page looks good enough. The PR opened by a member is already using the "correct" back logic.

**Comment by rafamanzo** [comment]
I'm still tending to eliminate such buttons. I hd a look at CodeClimate's project creation/edition and Gitlab's project edtion and none have such feature.

What do you think @mezuro/core ?

**Comment by diegoamc** [comment]
I'm still unsure about this too.
We have a lot of cases that may create different expectations of where `back` should go to.
If we intend to just redirect the user to the last visited page, I don't think we need to duplicate a feature present on browsers and may be better to just remove the buttons.

**Comment by wiltonsr** [comment]
I think that is important to cite that the browser back button redirect you back in history of the browser, not back in app navigation, and by this reason isn't appropriate for navigation purposes. So, if a user enters a page via a link like: http://localhost:3000/en/kalibro_configurations/1, they won't have valid navigation history to go back for http://localhost:3000/en/kalibro_configurations if he use the browser back button.

**Comment by diegoamc** [comment]
According to the [rails docs](http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to), the `back` option will

> generate a link to the referrer (a JavaScript back link will be used in place of a referrer if none exists)

So, if the [referrer](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer) does exist it should behave like the `back` button of browsers. 

When the referrer does not exist (like the example you gave), rails use a JavaScript back link. If you look in the [rails code](https://github.com/rails/rails/blob/f785413ce3d56f51f813cfd92c515c803ffde4d6/actionview/lib/action_view/helpers/url_helper.rb#L44) you'll see that it'll use a `history.back()` javascript function. That will also [behave like the back button of browsers](https://developer.mozilla.org/en-US/docs/Web/API/History_API). Your specific example works because we explicitly [programmed it to always go back to the index page](https://github.com/mezuro/prezento/blob/master/app/views/kalibro_configurations/show.html.erb#L61).

Finally, test using the url of a repository edit page (http://localhost:3000/en/repositories/1/edit), coming from a new tab or from another website, with the code you submitted on #385. You'll see that it will not go to the repository index page or the project show page.

Therefore, I keep my opinion that we don't need to duplicate a browser feature and would be better to remove all `back` buttons we have.

**Comment by wiltonsr** [comment]
Thank you for reply
After all that, I agree with the decision from remove all `back` buttons. But, I share the @DylanGuedes viewpoint that the [breadcrumb](http://v4-alpha.getbootstrap.com/components/breadcrumb/) would be a more elegant solution.

**Comment by diegoamc** [comment]
What do you think about starting by removing the `back` buttons?

**Comment by wiltonsr** [comment]
Perfect. Could you open the issue?
